// <auto-generated />
using CelilCavus.OgrenciKayitSistemi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CelilCavus.OgrenciKayitSistemi.Migrations
{
    [DbContext(typeof(KayitSistemiContext))]
    partial class KayitSistemiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CelilCavus.OgrenciKayitSistemi.Entites.Dersler", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ders_adi")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Ders Adi Tanimsiz");

                    b.Property<string>("ders_donemi")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Ders Dönemi Tanimsiz");

                    b.Property<string>("ders_hocasi")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Ders Hocasi Tanimsiz");

                    b.Property<string>("ders_kodu")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValue("00000");

                    b.HasKey("id");

                    b.ToTable("Derslers");
                });

            modelBuilder.Entity("CelilCavus.OgrenciKayitSistemi.Entites.Ogrenci", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ad")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Öğrenci Adi Tanimsiz");

                    b.Property<string>("bolum")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Öğrenci Bölüm Tanimsiz");

                    b.Property<string>("cinsiyet")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Öğrenci Cinsiyet Tanimsiz");

                    b.Property<int>("sinif")
                        .HasColumnType("int");

                    b.Property<string>("soyad")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Öğrenci Soyadi Tanimsiz.");

                    b.HasKey("id");

                    b.ToTable("Ogrencis");
                });
#pragma warning restore 612, 618
        }
    }
}
